default:
  adapter: postgresql
  database: postgres
  pool: 5

development:
  adapter: postgresql
  database: simple_blog_api_ror
  username: admin
  password: admin
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: simple_blog_api_ror
  username: admin
  password: admin
  encoding: unicode
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: simple_blog_api_ror
  username: admin
  password: admin
  encoding: unicode
  host: localhost
  pool: 5
